language: node_js
sudo: required
dist: trusty
node_js: stable
before_script:
- npm install -g bower polylint web-component-tester
- npm install arc-tools
- bower install
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- polylint
- xvfb-run wct
after_success:
- eval "$(ssh-agent -s)"
- ssh-add github_id_rsa
- ssh-add github_id_rsa.pem
- ./tasks/travis_deploy
cache:
  directories:
  - bower_components
before_install:
- openssl aes-256-cbc -K $encrypted_c6214cd3c769_key -iv $encrypted_c6214cd3c769_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- chmod +x tasks/travis_deploy
- chmod +x tasks/commit
- chmod 600 github_id_rsa
- chmod 600 github_id_rsa.pub
