language: node_js
sudo: required
dist: trusty
node_js: stable
before_script:
- apt-get install git
- npm install -g bower polylint web-component-tester arc-tools
- bower install
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- polylint
- xvfb-run wct
before_install:
- mkdir -p ~/.ssh
- openssl aes-256-cbc -K $encrypted_c6214cd3c769_key -iv $encrypted_c6214cd3c769_iv
  -in github_rsa.pub.enc -out ~\/.ssh/github_rsa.pub -d
- openssl aes-256-cbc -K $encrypted_c6214cd3c769_key -iv $encrypted_c6214cd3c769_iv
  -in github_rsa.enc -out ~\/.ssh/github_rsa -d
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "stage"]; then bash arc stage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "master"]; then bash echo "TODO release"; fi'
cache:
  directories:
  - node_modules
  - bower_components
