#!/bin/bash
set -e # Exit with nonzero exit code if anything fails

# Save some useful information
REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
SHA=`git rev-parse --verify HEAD`

chmod 600 github_id_rsa
eval `ssh-agent -s`
ssh-add github_id_rsa

# Now that we're all set up, we can push.
git push $SSH_REPO $1
