#!/usr/bin/env bash

if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && [[ "${TRAVIS_BRANCH}" == "stage" ]]; then
  echo "Updating stage branch and marging with master..."
  ./node_modules/.bin/arc stage
  exit
fi

if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && [[ "${TRAVIS_BRANCH}" == "master" ]]; then
  echo "Deploying release to master branch..."
  exit
fi
